### ISSUE TITLE
Workflow Group

### ISSUE THREAD

**Issue by RobertsFerreira** [RobertsFerreira/api_tbl_tcc#4]
**Todos vinculados a uma empresa**

- [x] Insert
   - [x] Criar dois Models
       - [x] Sem ID
       - [x] Com ID
   - [x] Service
   - [x] API
- [x] Update
   - [x] Service
   - [x] API
- [x] Search by Class
   - [x] Service
   - [x] API
- [x]  Search by Class and Data
   - [x] Service
   - [x] API
- [x] Delete
   - [x] Service
   - [x] API
